/// The font families Ludwig ships inside the app.
///
/// Generated from `~/Projects/ludwig-fonts/google_fonts_he_ar/` — every family
/// there covers Hebrew or Arabic and is licensed under the SIL Open Font
/// Licence 1.1, whose text ships alongside them in
/// `assets/google_fonts_ludwig/OFL-LICENSES.txt`.
///
/// **Why this list exists.** Upstream's font picker offers the entire Google
/// Fonts catalogue (~1,800 families) and downloads each one on demand. Ludwig
/// bundles its fonts and turns runtime fetching OFF, so offering a font we do
/// not ship would mean offering one that cannot load. The picker lists exactly
/// this set, and every entry works with the network unplugged.
///
/// The strings must match the keys of `GoogleFonts.asMap()`, because that is
/// what resolves a name to a font. There is a test asserting they do.
///
/// See `specs/fonts.md`. Regenerate rather than hand-edit.
class LudwigBundledFonts {
  const LudwigBundledFonts._();

  /// 111 families, all SIL OFL, all bundled.
  static const List<String> families = <String>[
    'Alef',
    'Alexandria',
    'Alkalami',
    'Almarai',
    'Alyamama',
    'Amatic SC',
    'Amiri',
    'Amiri Quran',
    'Aref Ruqaa',
    'Aref Ruqaa Ink',
    'Arimo',
    'Assistant',
    'Badeen Display',
    'Baloo Bhaijaan 2',
    'Beiruti',
    'Bellefair',
    'Blaka',
    'Blaka Hollow',
    'Blaka Ink',
    'Bona Nova',
    'Bona Nova SC',
    'Cairo',
    'Cairo Play',
    'Cardo',
    'Cascadia Code',
    'Cascadia Mono',
    'Changa',
    'Cousine',
    'David Libre',
    'El Messiri',
    'Estedad',
    'Frank Ruhl Libre',
    'Fredoka',
    'Fustat',
    'Gulzar',
    'Gveret Levin',
    'Handjet',
    'Harmattan',
    'Heebo',
    'IBM Plex Sans Arabic',
    'IBM Plex Sans Hebrew',
    'Jomhuria',
    'Karantina',
    'Katibeh',
    'Kufam',
    'Lalezar',
    'Lateef',
    'Lemonada',
    'Libertinus Serif',
    'Lunasima',
    'M PLUS 1p',
    'Mada',
    'Marhey',
    'Markazi Text',
    'Miriam Libre',
    'Mirza',
    'Noto Kufi Arabic',
    'Noto Naskh Arabic',
    'Noto Nastaliq Urdu',
    'Noto Rashi Hebrew',
    'Noto Sans Arabic',
    'Noto Sans Hebrew',
    'Noto Serif Hebrew',
    'Oi',
    'Open Sans',
    'Parastoo',
    'Playpen Sans Arabic',
    'Playpen Sans Hebrew',
    'Qahiri',
    'Rakkas',
    'Readex Pro',
    'Reem Kufi',
    'Reem Kufi Fun',
    'Reem Kufi Ink',
    'Rubik',
    'Rubik 80s Fade',
    'Rubik Beastly',
    'Rubik Broken Fax',
    'Rubik Bubbles',
    'Rubik Burned',
    'Rubik Dirt',
    'Rubik Distressed',
    'Rubik Doodle Shadow',
    'Rubik Doodle Triangles',
    'Rubik Gemstones',
    'Rubik Glitch',
    'Rubik Glitch Pop',
    'Rubik Iso',
    'Rubik Lines',
    'Rubik Maps',
    'Rubik Marker Hatch',
    'Rubik Maze',
    'Rubik Microbe',
    'Rubik Moonrocks',
    'Rubik Pixels',
    'Rubik Puddles',
    'Rubik Scribble',
    'Rubik Spray Paint',
    'Rubik Storm',
    'Rubik Vinyl',
    'Rubik Wet Paint',
    'Ruwudu',
    'Scheherazade New',
    'Secular One',
    'Solitreo',
    'Suez One',
    'Tajawal',
    'Varela Round',
    'Vazirmatn',
    'Vibes',
    'Zain',
  ];
}
